#!/usr/bin/env bash

./generate 50
./generate 50 | tac
./generate 100 
./generate 100 | tac
./generate 200
./generate 200 | tac
./generate 100
./generate 100 | tac
./generate 50 
./generate 50 | tac
sleep 10s
